### ISSUE TITLE
sitemap_news.xml is empty

### ISSUE THREAD

**Issue by limjh16** [skatkov/jekyll-news-sitemap#6]
I tried to add the gem into the Gemfile and include this plugin into _config.yml, but the sitemap_news.xml file is empty. It did generate that file so I think I added the plugin correctly. I followed the README to add all the fields into the _config.yml already.

**Comment by skatkov** [comment]
Thanks for reporting.

This gem is a work in progress since there are a couple of open questions related to sitemap_news I still didn't figure out.

So according to official documentation from google, `sitemap_news.xml` only should show posts from the last 2 days. This is basically how I implemented that currently.

But if `sitemap_news.xml` is completely empty, then Google doesn't consider it valid...

I was planning to solve that, by using 2 days as a default value, but giving an option to redefine it in _config.yml file.  But unfortunately, I didn't had time to implement it yeat.

**Comment by limjh16** [comment]
Ahh okay, I don't think I have any posts in the last 2 days, that explains it...
May I just ask how this plugin decides to generate the xml file? Is it everytime the jekyll site builds or does it regenerate it every few days?

**Comment by skatkov** [comment]
Everytime you generate your website sitemap_news.xml will get updated. It seems like a good idea to rebuild your website at least once a day (this is how I use it).

**Comment by rakarmegam** [comment]
Will it generate for newly added pages in last 2 days ? Currently it is not generating for pages for me.

**Comment by skatkov** [comment]
I probably messed up and ended up not using this gem. There are so little information about the standard for the sitemap, that I stopped working on this gem in frustration.

I highly recommend to try previous versions - it did work for sure at some point.

But keep in mind that you should always have at least one news every 2 days. Otherwise empty sitemap becomes invalid.
